on: 
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * MON-FRI'

jobs:
  sync:
    permissions:
      contents: write
    name: "NVD Data Sync"
    runs-on: ubuntu-latest
    container:
      image: python:3-alpine
    steps:
      - name: Install dependencies
        run: apk add --no-cache crane bash git
      - name: Configure git
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Sync
        run: ./scripts/sync.sh
      - name: Commit changes
        run: |
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git config user.name "github-actions[bot]"
            ./scripts/commit.sh
            git push